import './globals.css'
import { Inter } from 'next/font/google'
import { ApolloClient, InMemoryCache, ApolloProvider} from '@apollo/client';

const client = new ApolloClient ({
  uri: "http://localhost:8080/",
  cache: new InMemoryCache
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Li-NFT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ApolloClient client={client}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ApolloClient>
  )
}
